apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: readonly-role
  namespace: default
rules:
- apiGroups: [""] # "": default - Core API Group
  resources: ["*"]
  verbs: ["get, list"]
- apiGroups: ["apps"] # "": default - Core API Group
  resources: ["*"]
  verbs: ["get, list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-rolebind
  namespace: default
subjects:
- kind: ServiceAccount
  name: readonly-user
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io

  #